#! /bin/bash

#====================================================
# file: test.sh
#----------------------------------------------------
# - Test all examples for compilation and tests/
# By 
#====================================================

Testfold="tests"
Outfold="witnesses"
Builder=./src/main.native
TestCounter=0
SuccesCounter=0


#==== printr : print succes or failure ====
function printr 
{
    if [[ $# -lt 0 ]];then
        exit 1;
    else
        TestCounter=$((TestCounter+1))
        if [[ $1 -ne $2 ]];then
            echo -e "\033[1;31m[FAIL]\033[0m"
        else 
            SuccesCounter=$((SuccesCounter+1))
            echo -e "\033[1;33m[PASS]\033[0m"
        fi
    fi
}


#==== Normal Tests ====
StartTime=`date +%s`
echo ">> Testing Proof Algorithm <<"
for folder in ${Testfold}/*
do
    # must be dir
    if [ ! -d "$folder" ];then
        continue
    fi

    name=${folder##*/}
    printf "%s" "Testing :: $name "
    output="${Outfold}/${name}.ml"

    # test compilation and abort further tests if failed
    #echo ${folder}/m1.ml ${folder}/m2.ml ${folder}/m1.trace ${folder}/m2.trace $output
    $Builder ${folder}/m1.ml ${folder}/m2.ml ${folder}/m1.trace ${folder}/m2.trace $output 
    res=$?
    printr $res 0

done


#==== Final Result ====
echo -e "\n== FINAL RESULT =="
FAIL=0
printf "%s" "  "
if [[ $SuccesCounter -ne $TestCounter ]];then
    echo -ne "\033[1;31m[$SuccesCounter]\033[0m"
    FAIL=1
else 
    echo -ne "\033[1;33m[$SuccesCounter]\033[0m"
fi

echo -e " of \033[1;33m[$TestCounter]\033[0m Tests in $(expr `date +%s` - $StartTime)(s)"

exit $FAIL
